### ISSUE TITLE
Query execution error presentation

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-github-issue-notebooks#1] opened 2020-04-01 01:21 UTC
See screenshot. It's hard to find the actual error:

![image](https://user-images.githubusercontent.com/4674940/78089464-5c4e5d80-737c-11ea-9211-396dcb2e4216.png)

**Comment by jrieken** [comment] 2020-04-01 15:35
dupe of https://github.com/microsoft/vscode/issues/93893

**Closed by jrieken** 2020-04-01 15:35 UTC
