### ISSUE TITLE
Results differ from what GitHub returns

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-github-issue-notebooks#70] opened 2020-09-15 18:47 UTC
Using the [search of `repo:microsoft/vscode-python is:issue -label:"data science" is:open sort:reactions-+1-desc label:"type-enhancement"`](https://github.com/search?q=repo%3Amicrosoft%2Fvscode-python+is%3Aissue+-label%3A%22data+science%22+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22type-enhancement%22), I get the following results on GitHub directly:

![image](https://user-images.githubusercontent.com/54418/93250956-673d5480-f748-11ea-9d1e-5ab9f213665f.png)

But using the extension, I get the following results:

![image](https://user-images.githubusercontent.com/54418/93250989-72908000-f748-11ea-8991-76c1ec3654f5.png)

Notice how the third item differs. I checked and the result directly on GitHub is correct. I also verified via the REST API and I get the expected results there:
```sh
curl \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/search/issues?q=repo%3Amicrosoft%2Fvscode-python+is%3Aissue+-label%3A\"data+science\"+is%3Ao
pen+sort%3Areactions-%2B1-desc+label%3Atype-enhancement"
```

[gh_results.txt](https://github.com/microsoft/vscode-github-issue-notebooks/files/5227093/gh_results.txt)

**Comment by jrieken** [comment] 2020-09-16 14:48
dupe of https://github.com/microsoft/vscode-github-issue-notebooks/issues/68

**Closed by jrieken** 2020-09-16 14:48 UTC
